#!/usr/bin/env python3
"""Generates the OBJ geometry for the photovoltaic blocks.

Why a generator rather than a modelling package: this geometry is almost entirely
boxes at right angles, and the few that are not are a plate at a fixed tilt and a
handful of cups on a hub.  Written out from a script it is reviewable in a diff,
reproducible, and it cannot drift away from the figures it is built from - the
tilted rack really is at the mounting's 25 degrees because the number comes from
the same place the physics reads it.

    python3 tools/gen_pv_models.py

Writes into src/main/resources/assets/electricity/models/.

What the renderer needs from the output
---------------------------------------
The OBJ pipeline splits by object and then by material, and keys each group
``<object>_<material>``.  So every part that has to move independently is its own
``o`` block, and the renderer matches on the object prefix.  Anything named
``rotate_*`` is a moving part and the renderer is expected to know its pivot.

Everything is authored in block units with x and z running -0.5 to 0.5 and y from
0 upwards, because ObjRenderUtil puts the frame at the block's centre in x and z
and at its floor in y.  Tilted and tracked planes are authored *flat*: their tilt
is a matrix at draw time, never baked into the vertices, since the buffer cache is
keyed by block position and would otherwise have to be rebuilt every frame.
"""

import math
import os

OUT = os.path.join('src', 'main', 'resources', 'assets', 'electricity', 'models')

# Materials, and the texture each one resolves to.  ObjModel prefixes
# textures/block/ to whatever map_Kd names, so these are bare file names.
MATERIALS = {
    'module': 'pv_module.png',
    'frame': 'pv_frame.png',
    'steel': 'pv_steel.png',
    'cabinet': 'pv_cabinet.png',
    'display': 'pv_display.png',
    'instrument': 'pv_instrument.png',
}

# The tilt a fixed rack is built at, in degrees.  The same figure PvMounting
# declares, restated here rather than imported because a Python script cannot read
# a Java enum - so if one changes the other has to, and this comment is the note
# saying so.
FIXED_TILT_DEG = 25.0

# Half-width of the drive bay at the centre of a tracker, in blocks.
#
# A plane rotating about an axis sweeps a disc of radius equal to its own semi-width, so
# any fixed part inside that disc gets swept through.  Rather than trying to thread the
# piers and the drive between the module edges - which cannot be done, because the plane
# passes through every angle - the fixed parts live in a bay at the centre of the row and
# the modules stop short of it.  Nothing can then collide at any angle.
#
# It is also what a real independent-row tracker looks like: one bay with no module in it,
# because that is where the slew drive is.
DRIVE_BAY = 0.11


class Mesh:
    """Accumulates vertices, normals, texture coordinates and faces for one OBJ file."""

    def __init__(self):
        self.v = []
        self.vn = []
        self.vt = []
        self.objects = []  # (name, material, [faces]) with faces as index triples

    def _index(self, table, value):
        # OBJ indices are 1-based and shared across the whole file, so identical
        # vertices are pooled rather than repeated: it keeps the files a third of
        # the size and costs nothing to read back
        key = tuple(round(c, 6) for c in value)
        for i, existing in enumerate(table):
            if existing == key:
                return i + 1
        table.append(key)
        return len(table)

    def add_object(self, name, material):
        self.objects.append((name, material, []))
        return self.objects[-1][2]

    def quad(self, faces, corners, normal, uvs):
        indices = []
        n = self._index(self.vn, normal)
        for corner, uv in zip(corners, uvs):
            indices.append((self._index(self.v, corner), self._index(self.vt, uv), n))
        faces.append(indices)

    def write(self, path, mtl_name):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w') as f:
            f.write('# generated by tools/gen_pv_models.py - do not edit by hand\n')
            f.write('mtllib %s\n' % mtl_name)
            for x, y, z in self.v:
                f.write('v %.6f %.6f %.6f\n' % (x, y, z))
            for x, y, z in self.vn:
                f.write('vn %.4f %.4f %.4f\n' % (x, y, z))
            for u, v in self.vt:
                f.write('vt %.6f %.6f\n' % (u, v))
            for name, material, faces in self.objects:
                if not faces:
                    continue
                f.write('o %s\n' % name)
                f.write('usemtl %s\n' % material)
                for face in faces:
                    f.write('f ' + ' '.join('%d/%d/%d' % idx for idx in face) + '\n')


def write_mtl(path, materials):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write('# generated by tools/gen_pv_models.py - do not edit by hand\n')
        for name in materials:
            f.write('\nnewmtl %s\n' % name)
            f.write('Ns 250.000000\nKa 1.000000 1.000000 1.000000\nKs 0.500000 0.500000 0.500000\n')
            f.write('Ke 0.000000 0.000000 0.000000\nNi 1.500000\nd 1.000000\nillum 2\n')
            f.write('map_Kd %s\n' % MATERIALS[name])


def rotate(point, pivot, axis, degrees):
    """Rotates a point about an axis-aligned line through pivot."""
    if degrees == 0.0:
        return point
    a = math.radians(degrees)
    c, s = math.cos(a), math.sin(a)
    x, y, z = point[0] - pivot[0], point[1] - pivot[1], point[2] - pivot[2]
    if axis == 'x':
        y, z = y * c - z * s, y * s + z * c
    elif axis == 'y':
        x, z = x * c + z * s, -x * s + z * c
    else:
        x, y = x * c - y * s, x * s + y * c
    return (x + pivot[0], y + pivot[1], z + pivot[2])


def box(mesh, faces, lo, hi, uv_scale=1.0, rot=None):
    """Six quads, outward normals, each face mapped across the whole texture.

    uv_scale under one insets the mapping, which is how a long rail gets a strip of
    its texture rather than the whole thing stretched along it.
    """
    x0, y0, z0 = lo
    x1, y1, z1 = hi
    u1 = uv_scale

    corners = {
        'down': [(x0, y0, z1), (x1, y0, z1), (x1, y0, z0), (x0, y0, z0)],
        'up': [(x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1)],
        'north': [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0)],
        'south': [(x1, y0, z1), (x0, y0, z1), (x0, y1, z1), (x1, y1, z1)],
        'west': [(x0, y0, z1), (x0, y0, z0), (x0, y1, z0), (x0, y1, z1)],
        'east': [(x1, y0, z0), (x1, y0, z1), (x1, y1, z1), (x1, y1, z0)],
    }
    normals = {
        'down': (0, -1, 0), 'up': (0, 1, 0), 'north': (0, 0, -1),
        'south': (0, 0, 1), 'west': (-1, 0, 0), 'east': (1, 0, 0),
    }
    uvs = [(0.0, 0.0), (u1, 0.0), (u1, u1), (0.0, u1)]

    for face, pts in corners.items():
        normal = normals[face]
        if rot is not None:
            pivot, axis, degrees = rot
            pts = [rotate(p, pivot, axis, degrees) for p in pts]
            normal = rotate(normal, (0, 0, 0), axis, degrees)
        mesh.quad(faces, pts, normal, uvs)


def cylinder(mesh, faces, centre, axis, radius, half_length, sides=8, uv_scale=1.0):
    """A prism standing in for a tube: eight sides reads as round at this scale."""
    cx, cy, cz = centre
    ring = []
    for i in range(sides):
        a = 2.0 * math.pi * i / sides
        if axis == 'y':
            ring.append((cx + radius * math.cos(a), cz + radius * math.sin(a)))
        elif axis == 'z':
            ring.append((cx + radius * math.cos(a), cy + radius * math.sin(a)))
        else:
            ring.append((cy + radius * math.cos(a), cz + radius * math.sin(a)))

    def point(i, end):
        p, q = ring[i]
        if axis == 'y':
            return (p, cy + end * half_length, q)
        if axis == 'z':
            return (p, q, cz + end * half_length)
        return (cx + end * half_length, p, q)

    for i in range(sides):
        j = (i + 1) % sides
        a, b = point(i, -1), point(j, -1)
        c, d = point(j, 1), point(i, 1)
        nx = (a[0] + c[0]) / 2 - cx
        ny = (a[1] + c[1]) / 2 - cy
        nz = (a[2] + c[2]) / 2 - cz
        length = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
        u = i / sides * uv_scale
        u2 = (i + 1) / sides * uv_scale
        mesh.quad(faces, [a, b, c, d], (nx / length, ny / length, nz / length),
                  [(u, 0.0), (u2, 0.0), (u2, uv_scale), (u, uv_scale)])


# ---------------------------------------------------------------- flat table

def flat_table():
    """A ballasted table lying flat: two modules in portrait on a low frame.

    Three pixels tall, which is the collision box, so it reads as a panel from
    across a field and is walked over rather than round.
    """
    mesh = Mesh()

    legs = mesh.add_object('legs', 'steel')
    for x in (-0.42, 0.34):
        for z in (-0.42, 0.34):
            box(mesh, legs, (x, 0.0, z), (x + 0.08, 0.035, z + 0.08), uv_scale=0.25)

    frame = mesh.add_object('frame', 'frame')
    box(mesh, frame, (-0.46, 0.035, -0.46), (0.46, 0.075, -0.40), uv_scale=0.4)
    box(mesh, frame, (-0.46, 0.035, 0.40), (0.46, 0.075, 0.46), uv_scale=0.4)
    box(mesh, frame, (-0.46, 0.035, -0.40), (-0.40, 0.075, 0.40), uv_scale=0.4)
    box(mesh, frame, (0.40, 0.035, -0.40), (0.46, 0.075, 0.40), uv_scale=0.4)

    modules = mesh.add_object('modules', 'module')
    # two modules with a gap between them, which is where a real table's rails run
    box(mesh, modules, (-0.46, 0.075, -0.46), (-0.02, 0.11, 0.46))
    box(mesh, modules, (0.02, 0.075, -0.46), (0.46, 0.11, 0.46))
    return mesh


# ------------------------------------------------------------- tilted rack

def tilted_rack():
    """A fixed rack at the mounting's own tilt, tipping towards -z.

    Towards -z because the block's default facing is north and PvArrayBlock reads
    the plane's bearing off that facing, so the geometry and the physics have to
    agree about which way is downhill.
    """
    mesh = Mesh()
    tilt = FIXED_TILT_DEG
    pivot = (0.0, 0.10, 0.0)

    legs = mesh.add_object('legs', 'steel')
    # the low pair at the front, the tall pair behind: what makes the plane tilt
    for x in (-0.40, 0.32):
        box(mesh, legs, (x, 0.0, -0.44), (x + 0.08, 0.11, -0.36), uv_scale=0.3)
        box(mesh, legs, (x, 0.0, 0.36), (x + 0.08, 0.47, 0.44), uv_scale=0.3)

    frame = mesh.add_object('frame', 'frame')
    box(mesh, frame, (-0.46, 0.055, -0.47), (0.46, 0.095, 0.47), uv_scale=0.5,
        rot=(pivot, 'x', -tilt))

    modules = mesh.add_object('modules', 'module')
    box(mesh, modules, (-0.46, 0.095, -0.47), (-0.02, 0.13, 0.47), rot=(pivot, 'x', -tilt))
    box(mesh, modules, (0.02, 0.095, -0.47), (0.46, 0.13, 0.47), rot=(pivot, 'x', -tilt))
    return mesh


# ---------------------------------------------------- single-axis tracker

def single_axis():
    """A torque tube through a slew drive, with the module plane authored flat.

    The plane is flat because its tilt is a matrix at draw time: the buffer cache
    is keyed by block position and rebuilt only when the light changes, so baking a
    rotation into the vertices would freeze the row wherever it happened to be.

    The tube runs north-south, which is the only axis from which a row can follow a
    sun that travels east to west - and it is why PvArrayBlock forces a tracker to
    that orientation whatever direction the player was facing.

    The drive bay
    -------------
    A plane rotating about an axis sweeps a *disc* of radius equal to its own
    semi-width, so any fixed part inside that disc gets swept through - which is
    exactly what the first version of this model did, putting the drive housing at
    the tube's height where the modules pass over it twice a day.

    The fix is the one real trackers use.  The pier and the drive sit in a bay at the
    centre of the row and the modules stop short of it, so every fixed part lives in
    ``|z| <= DRIVE_BAY`` and every moving part in ``|z| >= DRIVE_BAY``.  Nothing can
    collide at any angle, and the row reads correctly: a real independent-row tracker
    has a bay with no module in it, because that is where the slew drive is.
    """
    mesh = Mesh()
    axis_y = 0.62
    bay = DRIVE_BAY

    pier = mesh.add_object('pier', 'steel')
    box(mesh, pier, (-0.16, 0.0, -0.16), (0.16, 0.05, 0.16), uv_scale=0.4)
    # one central pier rather than a pair, because a pair either side of the bay would
    # stand in the swept disc: within one block a real row has a pier every six metres
    box(mesh, pier, (-0.055, 0.05, -0.075), (0.055, axis_y, 0.075), uv_scale=0.3)

    motor = mesh.add_object('motor', 'cabinet')
    # the slew drive: a housing round the tube, wholly inside the bay
    box(mesh, motor, (-0.13, axis_y - 0.13, -0.085), (0.13, axis_y + 0.13, 0.085), uv_scale=0.6)

    tube = mesh.add_object('rotate_tube', 'steel')
    cylinder(mesh, tube, (0.0, axis_y, 0.0), 'z', 0.045, 0.48, uv_scale=0.5)

    # two bays of modules, two rows deep, which is the 2-up portrait layout a real
    # horizontal single axis carries
    modules = mesh.add_object('rotate_modules', 'module')
    rails = mesh.add_object('rotate_rails', 'frame')
    for z0, z1 in ((-0.48, -bay), (bay, 0.48)):
        box(mesh, modules, (-0.44, axis_y + 0.045, z0), (-0.02, axis_y + 0.075, z1))
        box(mesh, modules, (0.02, axis_y + 0.045, z0), (0.44, axis_y + 0.075, z1))
        # purlins along the tube rather than across it: a rail spanning the full width
        # would pass through the tube it is supposed to be clamped to
        for x0, x1 in ((-0.42, -0.36), (-0.16, -0.10), (0.10, 0.16), (0.36, 0.42)):
            box(mesh, rails, (x0, axis_y + 0.02, z0), (x1, axis_y + 0.045, z1), uv_scale=0.3)

    return mesh


# ------------------------------------------------------ dual-axis pedestal

def dual_axis():
    """A pedestal, an azimuth collar, and an elevation frame carrying the modules.

    Two moving groups, and the reason the azimuth one exists is worth stating: it
    turns to face the sun's bearing, which in this world is due east all morning
    and due west all afternoon.  It therefore swings a half turn at noon - and that
    is invisible, because at noon the elevation frame is lying flat and a flat plate
    turned about its own vertical axis looks identical.  Which is exactly what a
    real azimuth-elevation machine does as the sun crosses its zenith.

    The same drive bay as the single axis, and for the same reason: the yoke arms that
    carry the elevation axis used to reach exactly as high as the modules started, so
    they clashed at zero degrees and got swept through completely by eighty.  Now the
    arms sit inside ``|z| <= DRIVE_BAY`` and the modules outside it, which is also what
    a real pedestal frame looks like - a gap down the middle where the yoke comes up.

    The elevation tube through the yoke is the one place geometry is allowed to
    intersect, because that is a bearing: a cylinder turning about its own axis inside
    a housing sweeps nothing.
    """
    mesh = Mesh()
    top = 0.55
    bay = DRIVE_BAY + 0.005
    # the elevation axis, and the height the renderer measures back off the rotating
    # groups' own bounding box - so the two cannot disagree about where the pivot is
    pivot_y = top + 0.1975

    pedestal = mesh.add_object('pedestal', 'steel')
    box(mesh, pedestal, (-0.20, 0.0, -0.20), (0.20, 0.06, 0.20), uv_scale=0.5)
    cylinder(mesh, pedestal, (0.0, top / 2.0 + 0.03, 0.0), 'y', 0.085, top / 2.0 - 0.03, uv_scale=0.4)

    azimuth = mesh.add_object('rotate_azimuth', 'cabinet')
    cylinder(mesh, azimuth, (0.0, top + 0.05, 0.0), 'y', 0.10, 0.05, uv_scale=0.5)
    # the yoke arms, separated along the elevation axis rather than across it, so the
    # frame's own torque tube runs between them and the modules clear them entirely. Kept
    # narrow so the bay - and therefore the gap down the middle of the plane - can be too
    for z0, z1 in ((-0.095, -0.04), (0.04, 0.095)):
        box(mesh, azimuth, (-0.04, top + 0.09, z0), (0.04, pivot_y + 0.012, z1), uv_scale=0.3)

    elevation = mesh.add_object('rotate_elevation', 'frame')
    # the frame's torque tube, through the yoke bearings and out to both module bays
    cylinder(mesh, elevation, (0.0, pivot_y, 0.0), 'z', 0.03, 0.42, uv_scale=0.4)
    for z0, z1 in ((-0.46, -bay), (bay, 0.46)):
        # a cross member at the bay's *inner* edge, tying the purlins back to the tube
        inner = (z1 - 0.06, z1) if z1 < 0.0 else (z0, z0 + 0.06)
        box(mesh, elevation, (-0.42, pivot_y - 0.0275, inner[0]), (0.42, pivot_y - 0.0025, inner[1]), uv_scale=0.4)
        for x0, x1 in ((-0.42, -0.36), (-0.16, -0.10), (0.10, 0.16), (0.36, 0.42)):
            box(mesh, elevation, (x0, pivot_y - 0.0275, z0), (x1, pivot_y - 0.0025, z1), uv_scale=0.3)

    modules = mesh.add_object('rotate_elevation_modules', 'module')
    for z0, z1 in ((-0.46, -bay), (bay, 0.46)):
        box(mesh, modules, (-0.44, pivot_y - 0.0025, z0), (-0.02, pivot_y + 0.0275, z1))
        box(mesh, modules, (0.02, pivot_y - 0.0025, z0), (0.44, pivot_y + 0.0275, z1))

    return mesh


# ------------------------------------------------------------- the inverter

def inverter():
    """A cabinet with a door, a display and a cooling fan.

    Authored at the size of the commercial machine and scaled per product by the
    renderer, the same trick the turbines use: the catalogue spans a factor of two
    hundred and fifty in nameplate and the difference on screen is a transform
    rather than four assets.
    """
    mesh = Mesh()

    cabinet = mesh.add_object('cabinet', 'cabinet')
    box(mesh, cabinet, (-0.44, 0.0, -0.30), (0.44, 0.98, 0.28), uv_scale=0.9)
    # a plinth, because a cabinet standing straight on the ground rusts
    box(mesh, cabinet, (-0.46, 0.0, -0.32), (0.46, 0.05, 0.30), uv_scale=0.5)

    door = mesh.add_object('door', 'frame')
    box(mesh, door, (-0.40, 0.10, -0.335), (0.40, 0.90, -0.30), uv_scale=0.9)
    # the hinge side and the handle, which is what makes it read as a door
    box(mesh, door, (0.34, 0.42, -0.36), (0.40, 0.58, -0.335), uv_scale=0.2)

    display = mesh.add_object('display', 'display')
    box(mesh, display, (-0.28, 0.62, -0.345), (0.06, 0.80, -0.335))

    fan = mesh.add_object('rotate_fan', 'steel')
    # a five-bladed impeller behind a grille on the right-hand side
    for i in range(5):
        angle = i * 72.0
        box(mesh, fan, (0.455, 0.68 - 0.015, -0.015), (0.47, 0.68 + 0.015, 0.15),
            uv_scale=0.2, rot=((0.46, 0.68, 0.0), 'x', angle))

    grille = mesh.add_object('grille', 'steel')
    box(mesh, grille, (0.44, 0.52, -0.16), (0.455, 0.84, 0.16), uv_scale=0.4)

    insulator = mesh.add_object('insulator', 'instrument')
    cylinder(mesh, insulator, (0.30, 1.03, 0.0), 'y', 0.045, 0.05, uv_scale=0.3)
    return mesh


# --------------------------------------------------------- the met station

def met_mast():
    """A mast with seven instruments on a boom, an anemometer and a vane.

    Laid out the way a real one is: the radiometers on a boom pointing away from the
    mast so its shadow cannot fall on them, the radiation shield below them, the
    snow gauge on its own arm looking straight down at clear ground, and the wind
    sensors at the top clear of everything else.
    """
    mesh = Mesh()

    mast = mesh.add_object('mast', 'steel')
    cylinder(mesh, mast, (0.0, 0.48, 0.0), 'y', 0.035, 0.48, uv_scale=0.3)
    box(mesh, mast, (-0.12, 0.0, -0.12), (0.12, 0.04, 0.12), uv_scale=0.4)

    boom = mesh.add_object('boom', 'steel')
    box(mesh, boom, (-0.02, 0.70, 0.03), (0.02, 0.74, 0.42), uv_scale=0.3)
    box(mesh, boom, (-0.02, 0.44, 0.03), (0.02, 0.48, 0.30), uv_scale=0.3)

    # the three radiometers: global, diffuse under its shadow ring, and the
    # albedometer, which is two of them back to back
    pyranometer = mesh.add_object('pyranometer', 'instrument')
    cylinder(mesh, pyranometer, (0.0, 0.755, 0.16), 'y', 0.05, 0.02, uv_scale=0.4)
    cylinder(mesh, pyranometer, (0.0, 0.785, 0.16), 'y', 0.028, 0.015, uv_scale=0.3)

    diffuse = mesh.add_object('diffuse', 'instrument')
    cylinder(mesh, diffuse, (0.0, 0.755, 0.30), 'y', 0.05, 0.02, uv_scale=0.4)
    cylinder(mesh, diffuse, (0.0, 0.785, 0.30), 'y', 0.026, 0.014, uv_scale=0.3)
    # the shadow ring, which is what makes it a diffuse instrument at all
    box(mesh, diffuse, (-0.075, 0.78, 0.295), (0.075, 0.795, 0.305), uv_scale=0.2)

    albedometer = mesh.add_object('albedometer', 'instrument')
    cylinder(mesh, albedometer, (0.0, 0.755, 0.40), 'y', 0.045, 0.018, uv_scale=0.4)
    cylinder(mesh, albedometer, (0.0, 0.785, 0.40), 'y', 0.024, 0.013, uv_scale=0.3)
    # the downward-looking half: an albedometer is two pyranometers, one of them upside down
    cylinder(mesh, albedometer, (0.0, 0.715, 0.40), 'y', 0.024, 0.013, uv_scale=0.3)

    shield = mesh.add_object('shield', 'instrument')
    # a naturally aspirated radiation shield: a stack of plates with air between them
    for i in range(4):
        y = 0.40 + i * 0.022
        box(mesh, shield, (-0.055, y, 0.245), (0.055, y + 0.012, 0.355), uv_scale=0.4)

    snow = mesh.add_object('snow', 'cabinet')
    box(mesh, snow, (-0.03, 0.30, -0.34), (0.03, 0.36, -0.28), uv_scale=0.3)
    box(mesh, snow, (-0.02, 0.32, -0.28), (0.02, 0.34, 0.0), uv_scale=0.3)

    cups = mesh.add_object('rotate_cups', 'instrument')
    cylinder(mesh, cups, (0.0, 0.99, 0.0), 'y', 0.018, 0.03, uv_scale=0.2)
    for i in range(3):
        angle = i * 120.0
        box(mesh, cups, (0.10, 0.985, -0.035), (0.17, 1.03, 0.035),
            uv_scale=0.3, rot=((0.0, 1.0, 0.0), 'y', angle))
        box(mesh, cups, (0.02, 0.995, -0.008), (0.11, 1.01, 0.008),
            uv_scale=0.2, rot=((0.0, 1.0, 0.0), 'y', angle))

    vane = mesh.add_object('rotate_vane', 'frame')
    box(mesh, vane, (-0.01, 0.86, -0.02), (0.01, 0.90, 0.22), uv_scale=0.3)
    box(mesh, vane, (-0.012, 0.845, 0.14), (0.012, 0.925, 0.24), uv_scale=0.3)
    box(mesh, vane, (-0.02, 0.855, -0.09), (0.02, 0.895, -0.02), uv_scale=0.2)
    return mesh


MODELS = [
    ('pv_flat', flat_table, ('steel', 'frame', 'module')),
    ('pv_tilt', tilted_rack, ('steel', 'frame', 'module')),
    ('pv_track', single_axis, ('steel', 'cabinet', 'module', 'frame')),
    ('pv_dual', dual_axis, ('steel', 'cabinet', 'frame', 'module')),
    ('pv_inverter', inverter, ('cabinet', 'frame', 'display', 'steel', 'instrument')),
    ('met_mast', met_mast, ('steel', 'instrument', 'cabinet', 'frame')),
]


def main():
    for name, builder, materials in MODELS:
        mesh = builder()
        directory = os.path.join(OUT, name)
        mesh.write(os.path.join(directory, name + '.obj'), name + '.mtl')
        write_mtl(os.path.join(directory, name + '.mtl'), materials)
        groups = ['%s_%s' % (obj, material) for obj, material, faces in mesh.objects if faces]
        print('%-12s %2d objects, %3d vertices, groups: %s'
              % (name, len(mesh.objects), len(mesh.v), ', '.join(groups)))


if __name__ == '__main__':
    main()
