#!/usr/bin/env python3
"""The geometry the mod's own OBJ models are built from.

Why a library rather than a modelling package: this geometry has to be reviewable in a diff and
reproducible from the figures it is built from - a rack really is at the mounting's 25 degrees
because the number comes from the same place the physics reads it - and it has to keep the group
names the renderers bind to, which a package would rename on every export.

Everything is authored in block units with x and z running -0.5 to 0.5 and y from 0 upwards,
because ``ObjRenderUtil`` puts the frame at the block's centre in x and z and at its floor in y.

What the renderers need from the output
---------------------------------------
The OBJ pipeline splits by object and then by material, and keys each group ``<object>_<material>``.
So every part that has to move independently is its own ``o`` block:

* ``rotate_*``  a moving part; the renderer knows its pivot
* ``pivot_*``   a zero-size marker naming where something turns, never drawn
* ``harness*``  drawn only once a reel of cable has been worked into the machine
* ``insulator*``a wire fitting; ``ObjDefinitions`` names these and wires hang off their centres

How round is round
------------------
The turbine is the model everything else is being brought up to, and it answers this: its tower is
an **eighty**-sided prism and its insulator a **thirty-two**-sided one.  So a principal body - a
pole shaft, a mast, a torque tube, a pedestal column, a lantern - gets ``ROUND``, and a fitting a
player only ever sees from two metres away gets ``FITTING``.

What deliberately keeps six or four sides is the geometry that is genuinely faceted: a bolt head is
a hexagon, an I-beam pier is an I, a crossarm is a channel, a square torque tube is square.  Giving
those more sides would not be smoother, it would be wrong.
"""

import math
import os

# The turbine's own subdivisions, restated here because they are now the whole mod's.
ROUND = 80
FITTING = 32
# A hexagon, for the things that are hexagons.
HEX = 6


class Mesh:
    """Accumulates vertices, normals, texture coordinates and faces for one OBJ file."""

    def __init__(self):
        self.v = []
        self.vn = []
        self.vt = []
        self.objects = []  # (name, material, [faces]) with faces as index triples
        self._pool = {}

    def _index(self, table, value, pool_key):
        # OBJ indices are 1-based and shared across the whole file, so identical vertices are
        # pooled rather than repeated: it keeps the files a third of the size and costs nothing to
        # read back.  A dictionary rather than a linear scan, because at eighty sides a prism has
        # enough vertices that a scan over the whole table per vertex is minutes rather than seconds.
        key = tuple(round(c, 6) for c in value)
        pool = self._pool.setdefault(pool_key, {})
        found = pool.get(key)
        if found is not None:
            return found
        table.append(key)
        pool[key] = len(table)
        return len(table)

    def add_object(self, name, material):
        faces = []
        self.objects.append((name, material, faces))
        return faces

    def faces(self, name, material):
        """The face list for one object-material pair, made if it is not there yet."""
        for existing_name, existing_material, faces in self.objects:
            if existing_name == name and existing_material == material:
                return faces
        return self.add_object(name, material)

    def quad(self, faces, corners, normal, uvs):
        indices = []
        n = self._index(self.vn, normal, 'vn')
        for corner, uv in zip(corners, uvs):
            indices.append((self._index(self.v, corner, 'v'), self._index(self.vt, uv, 'vt'), n))
        faces.append(indices)

    def write(self, path, mtl_name, source):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w') as f:
            f.write('# generated by tools/%s - do not edit by hand\n' % source)
            f.write('mtllib %s\n' % mtl_name)
            for x, y, z in self.v:
                f.write('v %.6f %.6f %.6f\n' % (x, y, z))
            for x, y, z in self.vn:
                f.write('vn %.4f %.4f %.4f\n' % (x, y, z))
            for u, v in self.vt:
                f.write('vt %.6f %.6f\n' % (u, v))
            for name, material, faces in self.objects:
                if not faces:
                    continue
                f.write('o %s\n' % name)
                f.write('usemtl %s\n' % material)
                for face in faces:
                    f.write('f ' + ' '.join('%d/%d/%d' % idx for idx in face) + '\n')

    def stats(self):
        return len(self.v), sum(len(faces) for _, _, faces in self.objects)


def write_mtl(path, materials, textures, source):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write('# generated by tools/%s - do not edit by hand\n' % source)
        for name in materials:
            f.write('\nnewmtl %s\n' % name)
            f.write('Ns 250.000000\nKa 1.000000 1.000000 1.000000\nKs 0.500000 0.500000 0.500000\n')
            f.write('Ke 0.000000 0.000000 0.000000\nNi 1.500000\nd 1.000000\nillum 2\n')
            f.write('map_Kd %s\n' % textures[name])


# ------------------------------------------------------------------ transforms

def rotate(point, pivot_point, axis, degrees):
    """Rotates a point about an axis-aligned line through a pivot."""
    if degrees == 0.0:
        return point
    a = math.radians(degrees)
    c, s = math.cos(a), math.sin(a)
    x, y, z = point[0] - pivot_point[0], point[1] - pivot_point[1], point[2] - pivot_point[2]
    if axis == 'x':
        y, z = y * c - z * s, y * s + z * c
    elif axis == 'y':
        x, z = x * c + z * s, -x * s + z * c
    else:
        x, y = x * c - y * s, x * s + y * c
    return (x + pivot_point[0], y + pivot_point[1], z + pivot_point[2])


def pivot(mesh, name, point, material='steel'):
    """Marks where a moving part turns, as a zero-size group of its own.

    The renderer used to find a pivot by taking the centre of the rotating group's bounding box,
    which is exact for anything symmetric about its own axis and wrong for everything else - three
    anemometer cups at 120 degrees have a box centre nowhere near the mast.  Six degenerate quads
    draw nothing, the bounding box is the point exactly, and the renderer reads it.
    """
    box(mesh, mesh.faces('pivot_' + name, material), point, point)


# ------------------------------------------------------------------ boxes

FACES = ('down', 'up', 'north', 'south', 'west', 'east')


def box(mesh, faces, lo, hi, uv_scale=1.0, rot=None, only=None, uv=None, uv_rot=0):
    """Six quads, outward normals, each face mapped across the whole texture.

    ``rot`` is one ``(pivot, axis, degrees)`` or a sequence of them applied in order.

    ``uv_scale`` under one insets the mapping, which is how a long rail gets a strip of its texture
    rather than the whole thing stretched along it.  ``uv`` gives an explicit sub-rectangle instead,
    which is what keeps a cell the same size on every mounting: a module drawn on a shorter box
    takes fewer rows of the picture rather than squeezing all of them in.  ``uv_rot`` turns the
    mapping by whole quarters, for a module whose long axis runs the other way.  ``only`` emits a
    single named face, which is what lets clad_box split a box across materials.
    """
    x0, y0, z0 = lo
    x1, y1, z1 = hi

    corners = {
        'down': [(x0, y0, z1), (x1, y0, z1), (x1, y0, z0), (x0, y0, z0)],
        'up': [(x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1)],
        'north': [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0)],
        'south': [(x1, y0, z1), (x0, y0, z1), (x0, y1, z1), (x1, y1, z1)],
        'west': [(x0, y0, z1), (x0, y0, z0), (x0, y1, z0), (x0, y1, z1)],
        'east': [(x1, y0, z0), (x1, y0, z1), (x1, y1, z1), (x1, y1, z0)],
    }
    normals = {
        'down': (0, -1, 0), 'up': (0, 1, 0), 'north': (0, 0, -1),
        'south': (0, 0, 1), 'west': (-1, 0, 0), 'east': (1, 0, 0),
    }

    # Which corner of the texture goes on which corner of the face, and it is not the same for all
    # six.  The corner lists above are wound for outward normals, which is what the renderer needs,
    # and a texture laid on them in the obvious order comes out mirrored on all four sides: the
    # first corner of a side face is its low-x (or low-z) end, and from outside the block that end
    # is on the right rather than the left.  The lid has the opposite problem - its first corner is
    # the one nearest north, which is the top of the picture on screen, while the loader reads
    # texture v from the bottom.  So the sides get their u reversed and the lid its v.
    u0, v0, u1, v1 = uv if uv else (0.0, 0.0, uv_scale, uv_scale)
    plain = [(u0, v0), (u1, v0), (u1, v1), (u0, v1)]
    flipped_u = [(u1, v0), (u0, v0), (u0, v1), (u1, v1)]
    flipped_v = [(u0, v1), (u1, v1), (u1, v0), (u0, v0)]
    mapping = {
        'down': plain, 'up': flipped_v,
        'north': flipped_u, 'south': flipped_u, 'west': flipped_u, 'east': flipped_u,
    }

    for face, pts in corners.items():
        if only is not None and face != only:
            continue

        uvs = mapping[face]
        if uv_rot:
            shift = (uv_rot // 90) % 4
            uvs = uvs[shift:] + uvs[:shift]
        normal = normals[face]
        if rot is not None:
            # One rotation or a list of them, applied in order.  Two are needed by anything that is both
            # pitched and spun - a fan blade has an angle of attack *and* a position round the hub, and
            # with a single rotation it can only have one of the two.
            for pivot_point, axis, degrees in ([rot] if isinstance(rot[1], str) else rot):
                pts = [rotate(p, pivot_point, axis, degrees) for p in pts]
                normal = rotate(normal, (0, 0, 0), axis, degrees)
        mesh.quad(faces, pts, normal, uvs)


def clad_box(mesh, name, lo, hi, sides, uv_scale=1.0, rot=None, uv=None, uv_rot=0):
    """A box whose six faces are not all the same material.

    ``sides`` maps face names to materials, with ``'*'`` standing for the rest.  Each face goes
    into its own material's section, which is how a module can be cells on top, a backsheet
    underneath and frame all round while still being one part as far as the renderer is concerned.
    """
    for face in FACES:
        material = sides.get(face, sides['*'])
        box(mesh, mesh.faces(name, material), lo, hi, uv_scale=uv_scale, rot=rot, only=face,
            uv=uv if not isinstance(uv, dict) else uv.get(face, uv.get('*')), uv_rot=uv_rot)


# ------------------------------------------------------------------ prisms

def ring_points(radius, sides, phase=0.0):
    return [(radius * math.cos(phase + 2.0 * math.pi * i / sides),
             radius * math.sin(phase + 2.0 * math.pi * i / sides)) for i in range(sides)]


def cylinder(mesh, faces, centre, axis, radius, half_length, sides=FITTING, uv_scale=1.0,
             caps=None, taper=1.0, phase=0.0, uv_along=1.0, cap_ends=(-1, 1), uv=None):
    """A prism standing in for a tube.

    ``taper`` is the radius at the far end as a fraction of the near one, which is how a spun
    concrete pole and a two-section mast are made: both are cones, and drawing them as cylinders is
    the single clearest sign of a model nobody measured.

    ``caps`` closes the ends listed in ``cap_ends`` into that face list.  Without them a mast is a hole
    when you look down it and a radiometer has no dome to catch the light.  Fanned into quads rather
    than left as one polygon, because the render type consumes quads and the loader triangulates fans
    cleanly.
    """
    cx, cy, cz = centre
    near = ring_points(radius, sides, phase)
    far = ring_points(radius * taper, sides, phase)

    def point(i, end):
        p, q = (far if end > 0 else near)[i]
        if axis == 'y':
            return (cx + p, cy + end * half_length, cz + q)
        if axis == 'z':
            return (cx + p, cy + q, cz + end * half_length)
        return (cx + end * half_length, cy + p, cz + q)

    for i in range(sides):
        j = (i + 1) % sides
        a, b = point(i, -1), point(j, -1)
        c, d = point(j, 1), point(i, 1)
        nx = (a[0] + c[0]) / 2 - cx
        ny = (a[1] + c[1]) / 2 - cy
        nz = (a[2] + c[2]) / 2 - cz
        if axis == 'y':
            ny = 0.0
        elif axis == 'z':
            nz = 0.0
        else:
            nx = 0.0
        length = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
        if uv is None:
            u = i / sides * uv_scale
            u2 = (i + 1) / sides * uv_scale
            v0, v1 = 0.0, uv_along * uv_scale
        else:
            # An explicit window, for a fitting whose texture is a strip along its own length rather
            # than a tile: a plug's knurled nut, its barrel and its nose are three bands of one
            # drawing, and each segment has to take its own.
            u = uv[0] + (uv[2] - uv[0]) * i / sides
            u2 = uv[0] + (uv[2] - uv[0]) * (i + 1) / sides
            v0, v1 = uv[1], uv[3]
        mesh.quad(faces, [a, b, c, d], (nx / length, ny / length, nz / length),
                  [(u, v0), (u2, v0), (u2, v1), (u, v1)])

    if caps is None:
        return

    normal = {'x': (1.0, 0.0, 0.0), 'y': (0.0, 1.0, 0.0), 'z': (0.0, 0.0, 1.0)}[axis]
    # ``cap_ends`` is which ends are closed, and it matters wherever sections are stacked: a mast in two
    # pieces with a coupling between them has four internal ends, and capping all of them puts four
    # discs on two planes where nothing can see them and the depth buffer resolves them differently
    # per pixel per frame.
    for end in cap_ends:
        outward = tuple(component * end for component in normal)
        ring = far if end > 0 else near
        span = radius * (taper if end > 0 else 1.0) * 2.0

        def uv(i, ring=ring, span=span):
            p, q = ring[i]
            return (0.5 + p / span, 0.5 + q / span)

        order = list(range(sides)) if end > 0 else list(range(sides - 1, -1, -1))
        for i in range(1, sides - 2, 2):
            corners = [order[0], order[i], order[i + 1], order[i + 2]]
            mesh.quad(caps, [point(k, end) for k in corners], outward, [uv(k) for k in corners])


def hemisphere(mesh, faces, centre, radius, sides=FITTING, rings=6, up=1, squash=1.0, uv_scale=1.0):
    """A dome: a pole cap, a lantern top, a bollard head.

    Rings of quads with a fan at the pole, which keeps every face a quad.  ``squash`` under one
    flattens it, because most caps in the world are shallower than half a sphere.
    """
    cx, cy, cz = centre
    for r in range(rings):
        a0 = (math.pi / 2) * r / rings
        a1 = (math.pi / 2) * (r + 1) / rings
        r0, r1 = math.cos(a0) * radius, math.cos(a1) * radius
        y0 = cy + up * math.sin(a0) * radius * squash
        y1 = cy + up * math.sin(a1) * radius * squash
        lower = ring_points(r0, sides)
        upper = ring_points(r1, sides)
        for i in range(sides):
            j = (i + 1) % sides
            a = (cx + lower[i][0], y0, cz + lower[i][1])
            b = (cx + lower[j][0], y0, cz + lower[j][1])
            c = (cx + upper[j][0], y1, cz + upper[j][1])
            d = (cx + upper[i][0], y1, cz + upper[i][1])
            nx = (a[0] + c[0]) / 2 - cx
            ny = up * radius * (1.0 - math.cos((a0 + a1) / 2)) * 0.6 + 0.35 * up * radius
            nz = (a[2] + c[2]) / 2 - cz
            length = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
            v0 = r / rings * uv_scale
            v1 = (r + 1) / rings * uv_scale
            u = i / sides * uv_scale
            u2 = (i + 1) / sides * uv_scale
            mesh.quad(faces, [a, b, c, d], (nx / length, ny / length, nz / length),
                      [(u, v0), (u2, v0), (u2, v1), (u, v1)])


# ------------------------------------------------------------------ structural profiles

def ibeam(mesh, faces, lo, hi, axis='y', web=0.28, flange=0.22, uv_scale=0.3, rot=None):
    """An I-section: two flanges and a web between them.

    What a driven pier and a rack post actually are, and the reason to draw the profile rather than
    a plain box is that the flanges catch the light differently from the web - which is most of what
    says *steel section* rather than *grey stick* at any distance.

    ``web`` and ``flange`` are fractions of the section's own width.
    """
    x0, y0, z0 = lo
    x1, y1, z1 = hi
    if axis == 'y':
        width, depth = x1 - x0, z1 - z0
        mid_x = (x0 + x1) / 2
        box(mesh, faces, (x0, y0, z0), (x1, y1, z0 + depth * flange), uv_scale=uv_scale, rot=rot)
        box(mesh, faces, (x0, y0, z1 - depth * flange), (x1, y1, z1), uv_scale=uv_scale, rot=rot)
        box(mesh, faces, (mid_x - width * web / 2, y0, z0 + depth * flange),
            (mid_x + width * web / 2, y1, z1 - depth * flange), uv_scale=uv_scale, rot=rot)
    else:
        # a horizontal I, used for a purlin: flanges top and bottom, web between
        height = y1 - y0
        box(mesh, faces, (x0, y0, z0), (x1, y0 + height * flange, z1), uv_scale=uv_scale, rot=rot)
        box(mesh, faces, (x0, y1 - height * flange, z0), (x1, y1, z1), uv_scale=uv_scale, rot=rot)
        mid_z = (z0 + z1) / 2
        span = (z1 - z0) * web / 2
        box(mesh, faces, (x0, y0 + height * flange, mid_z - span),
            (x1, y1 - height * flange, mid_z + span), uv_scale=uv_scale, rot=rot)


def channel(mesh, faces, lo, hi, along='z', web=0.26, uv_scale=0.3, opening='up', rot=None):
    """A C-section: a back with two legs turned off it.

    A crossarm, a rack purlin and a module rail are all channels.  ``opening`` is which way the
    legs point, because a purlin's open side faces down so water leaves it.
    """
    x0, y0, z0 = lo
    x1, y1, z1 = hi
    height = y1 - y0
    thick_y = height * web
    if along == 'z':
        width = x1 - x0
        thick_x = width * web
        if opening in ('up', 'down'):
            back_y = (y0, y0 + thick_y) if opening == 'up' else (y1 - thick_y, y1)
            box(mesh, faces, (x0, back_y[0], z0), (x1, back_y[1], z1), uv_scale=uv_scale, rot=rot)
            box(mesh, faces, (x0, y0, z0), (x0 + thick_x, y1, z1), uv_scale=uv_scale, rot=rot)
            box(mesh, faces, (x1 - thick_x, y0, z0), (x1, y1, z1), uv_scale=uv_scale, rot=rot)
        else:
            back_x = (x0, x0 + thick_x) if opening == 'east' else (x1 - thick_x, x1)
            box(mesh, faces, (back_x[0], y0, z0), (back_x[1], y1, z1), uv_scale=uv_scale, rot=rot)
            box(mesh, faces, (x0, y0, z0), (x1, y0 + thick_y, z1), uv_scale=uv_scale, rot=rot)
            box(mesh, faces, (x0, y1 - thick_y, z0), (x1, y1, z1), uv_scale=uv_scale, rot=rot)
    else:
        depth = z1 - z0
        thick_z = depth * web
        back_y = (y0, y0 + thick_y) if opening == 'up' else (y1 - thick_y, y1)
        box(mesh, faces, (x0, back_y[0], z0), (x1, back_y[1], z1), uv_scale=uv_scale, rot=rot)
        box(mesh, faces, (x0, y0, z0), (x1, y1, z0 + thick_z), uv_scale=uv_scale, rot=rot)
        box(mesh, faces, (x0, y0, z1 - thick_z), (x1, y1, z1), uv_scale=uv_scale, rot=rot)


def angle(mesh, faces, lo, hi, along='z', web=0.30, uv_scale=0.3, rot=None):
    """An L-section: a brace, a bracket, a mounting cleat."""
    x0, y0, z0 = lo
    x1, y1, z1 = hi
    if along == 'z':
        box(mesh, faces, (x0, y0, z0), (x1, y0 + (y1 - y0) * web, z1), uv_scale=uv_scale, rot=rot)
        box(mesh, faces, (x0, y0, z0), (x0 + (x1 - x0) * web, y1, z1), uv_scale=uv_scale, rot=rot)
    elif along == 'x':
        box(mesh, faces, (x0, y0, z0), (x1, y0 + (y1 - y0) * web, z1), uv_scale=uv_scale, rot=rot)
        box(mesh, faces, (x0, y0, z0), (x1, y1, z0 + (z1 - z0) * web), uv_scale=uv_scale, rot=rot)
    else:
        box(mesh, faces, (x0, y0, z0), (x0 + (x1 - x0) * web, y1, z1), uv_scale=uv_scale, rot=rot)
        box(mesh, faces, (x0, y0, z0), (x1, y1, z0 + (z1 - z0) * web), uv_scale=uv_scale, rot=rot)


def strut(mesh, faces, p0, p1, half, thick=None, uv_scale=0.2):
    """A beam between two arbitrary points: a brace, a stay, an actuator, a guy.

    Written as an orthonormal frame rather than as a box with a rotation, because a diagonal is the
    one part whose two ends are both given: a rotation has to be solved for from them, and solving
    it by eye is what had a rack's braces crossing each other and poking out of the block.
    """
    thick = half if thick is None else thick
    d = [p1[i] - p0[i] for i in range(3)]
    length = math.sqrt(sum(c * c for c in d)) or 1.0
    d = [c / length for c in d]
    # any axis not parallel to the beam will do for the first cross product
    other = (0.0, 1.0, 0.0) if abs(d[1]) < 0.9 else (1.0, 0.0, 0.0)
    right = [other[1] * d[2] - other[2] * d[1], other[2] * d[0] - other[0] * d[2],
             other[0] * d[1] - other[1] * d[0]]
    norm = math.sqrt(sum(c * c for c in right)) or 1.0
    right = [c / norm for c in right]
    up = [d[1] * right[2] - d[2] * right[1], d[2] * right[0] - d[0] * right[2],
          d[0] * right[1] - d[1] * right[0]]

    def corner(end, s_right, s_up):
        base = p1 if end else p0
        return tuple(base[i] + right[i] * s_right * half + up[i] * s_up * thick for i in range(3))

    faces_spec = (
        ((0, -1, -1), (0, 1, -1), (1, 1, -1), (1, -1, -1), [-u for u in up]),
        ((0, -1, 1), (1, -1, 1), (1, 1, 1), (0, 1, 1), up),
        ((0, -1, -1), (1, -1, -1), (1, -1, 1), (0, -1, 1), [-r for r in right]),
        ((0, 1, -1), (0, 1, 1), (1, 1, 1), (1, 1, -1), right),
        ((0, -1, -1), (0, -1, 1), (0, 1, 1), (0, 1, -1), [-c for c in d]),
        ((1, -1, -1), (1, 1, -1), (1, 1, 1), (1, -1, 1), d),
    )
    for a, b, c, e, normal in faces_spec:
        pts = [corner(*a), corner(*b), corner(*c), corner(*e)]
        mesh.quad(faces, pts, tuple(normal),
                  [(0.0, 0.0), (uv_scale, 0.0), (uv_scale, uv_scale), (0.0, uv_scale)])


def bolt(mesh, faces, centre, axis, radius, length, uv_scale=0.2, head=1.7, washer=True):
    """A bolt: a hexagon head on a shank, with a washer under it.

    Six sides, and that is not a saving - a bolt head *is* a hexagon.  This is the one part of the
    mod where the low count is the accurate one.
    """
    cx, cy, cz = centre
    step = {'x': (length, 0, 0), 'y': (0, length, 0), 'z': (0, 0, length)}[axis]
    shank = (cx + step[0] / 2, cy + step[1] / 2, cz + step[2] / 2)
    cylinder(mesh, faces, shank, axis, radius, length / 2, sides=HEX, uv_scale=uv_scale)
    if washer:
        cylinder(mesh, faces, centre, axis, radius * head * 1.15, length * 0.06, sides=FITTING,
                 uv_scale=uv_scale, caps=faces)
    cylinder(mesh, faces, (cx + step[0] * 0.10, cy + step[1] * 0.10, cz + step[2] * 0.10), axis,
             radius * head, length * 0.10, sides=HEX, uv_scale=uv_scale, caps=faces,
             phase=math.pi / 6)


def sheds(mesh, faces, centre, radius, height, count=3, sides=FITTING, uv_scale=0.5, taper=0.72):
    """An insulator: a stack of skirts on a core, each wider at its lower rim.

    A pin insulator's whole job is to make the surface path from conductor to pin long, and the way
    it does that is the shape - a petticoat under each shed.  Drawn as a stack of shallow cones,
    which is what it is.
    """
    cx, cy, cz = centre
    step = height / count
    for i in range(count):
        y = cy + i * step
        wide = radius * (1.0 - i * (1.0 - taper) / max(1, count))
        # the shed: a cone, widest at the bottom rim, and the rim itself as a thin band so the
        # skirt has an edge rather than a knife edge
        cylinder(mesh, faces, (cx, y + step * 0.30, cz), 'y', wide, step * 0.30, sides=sides,
                 uv_scale=uv_scale, taper=0.55)
        cylinder(mesh, faces, (cx, y + step * 0.04, cz), 'y', wide, step * 0.04, sides=sides,
                 uv_scale=uv_scale, caps=faces)
        # the core between one shed and the next
        cylinder(mesh, faces, (cx, y + step * 0.75, cz), 'y', wide * 0.52, step * 0.20,
                 sides=sides, uv_scale=uv_scale)
    cylinder(mesh, faces, (cx, cy + height, cz), 'y', radius * taper * 0.62, step * 0.10,
             sides=sides, uv_scale=uv_scale, caps=faces)


def pin_insulator(mesh, porcelain, steel, centre, diameter, sides=FITTING, spindle=True):
    """The mod's one insulator: an ANSI 55-4 pin insulator in brown glazed porcelain.

    One shape, on every machine a wire clips to.  There used to be four - brown pin insulators on the
    pole and the kiosk, a *white* one on the inverter because it had been given the instrument material
    by mistake, a stack of green plastic discs on the turbine and a tall bushing on the cabin.  A fitting
    that appears on five objects should be the same fitting on all five: a distribution insulator is a
    catalogue part, and whoever built the line bought the same one for every structure on it.

    The proportions are the real ones.  ANSI 55-4 - the 11 kV workhorse - is 142 mm across its widest
    shed and 111 mm tall, so it is *wider than it is tall*, which is the one thing every old version got
    wrong: all of them were tall stacks and a pin insulator is a squat one.

    One profile, revolved
    ---------------------
    Drawn as a single surface of revolution rather than as a stack of cones, and that is a correctness
    fix rather than a tidy-up.  Stacked, each shed was a cone whose top was wider than the core above
    it, so between the two sat an annulus with no surface in it - and since these models are drawn
    without back-face culling, those annuli were holes you could see through the porcelain.  A profile
    closes by construction: a radius that steps in draws the step.

    Reading the contour from the bottom up, it is the real object part by part: the underside of the
    lower petticoat, its rim, the cone up to the neck, the neck, the upper shed and its rim, the head,
    the groove round the head's flank for a conductor running past, the groove round the top that a
    conductor terminating here is tied into, and the crown over it that keeps the tie wire on.  Those
    last three are what makes the silhouette recognisable at ten metres; without them a shed stack reads
    as a stack of plates.
    """
    cx, cy, cz = centre
    d, h = diameter, diameter * 0.78

    # (radius, height) as fractions of the diameter and the height, bottom centre to top centre.
    contour = [
        (0.000, 0.000),
        (0.500, 0.000),   # the lower petticoat's rim, seen from underneath
        (0.300, 0.290),   # the cone up to the neck
        (0.255, 0.290),   # in to the neck
        (0.255, 0.340),
        (0.400, 0.340),   # out to the upper shed's rim
        (0.245, 0.565),   # its cone
        (0.235, 0.565),   # in to the upper neck
        (0.235, 0.660),
        (0.290, 0.660),   # out to the head
        (0.290, 0.712),
        (0.238, 0.712),   # the side groove, for a conductor running past
        (0.238, 0.768),
        (0.290, 0.768),
        (0.290, 0.812),
        (0.188, 0.812),   # the top groove, for one that terminates here
        (0.188, 0.898),
        (0.266, 0.898),   # out to the crown that holds the tie wire in
        (0.224, 1.000),
        (0.000, 1.000),
    ]
    lathe(mesh, porcelain, centre, [(r * d, y * h) for r, y in contour], sides=sides,
          uv_scale=1.0, uv_along=1.0)

    # The spindle: hot-dip galvanised steel, with the lead thimble the porcelain is cemented onto.  Its
    # own group, because the wire hangs from the centre of the insulator group's bounding box and steel
    # inside that group would drag the anchor down towards the crossarm.
    if spindle:
        # half the sides: it is a spindle 8 mm across, mostly inside the porcelain, and eight of these
        # on one pole is the heaviest geometry in the mod
        lathe(mesh, steel, (cx, cy, cz), [
            (0.000, -0.34 * h), (0.085 * d, -0.34 * h),
            (0.085 * d, -0.10 * h), (0.118 * d, -0.08 * h),
            (0.118 * d, -0.005 * h), (0.000, -0.005 * h),
        ], sides=max(8, sides // 2), uv_scale=1.0, uv_along=1.0)


def tube(mesh, faces, points, radius, sides=FITTING, uv_scale=1.0, uv_along=1.0, caps=None):
    """A round tube swept along a polyline: the only way to draw a cable that turns.

    ``cylinder`` is axis-aligned, which is enough for a mast or a bushing and no use at all for a bend.
    This carries a ring of ``sides`` vertices along the path, orienting each ring to the average of the
    directions either side of its point - so a corner comes out mitred rather than kinked, and a run of
    short segments round a quarter circle comes out as a curve.

    The frame is built by carrying a reference vector along the path rather than by choosing one per
    ring, because choosing per ring twists the tube: two consecutive rings whose 'up' happened to be
    picked differently put a quarter turn into the mesh between them, and on a black cable that reads
    as a crease.

    ``uv_scale`` is how much of the texture goes round the circumference and ``uv_along`` how much runs
    along the length.  Both default to exactly one, and that is not a style choice: a block model's
    texture lives in the block atlas, so a uv past one does not tile - it samples whatever sprite the
    atlas happens to have put next door.  Which is precisely what broke the first version of the cable,
    and it is invisible in a previewer that binds one texture at a time.
    """
    path = [tuple(float(c) for c in point) for point in points]
    if len(path) < 2:
        return

    def norm(v):
        length = math.sqrt(sum(c * c for c in v)) or 1.0
        return (v[0] / length, v[1] / length, v[2] / length)

    def cross(a, b):
        return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])

    def sub(a, b):
        return (a[0] - b[0], a[1] - b[1], a[2] - b[2])

    # the direction at each point: the segment's own at the ends, the average of the two at a corner
    segments = [norm(sub(path[i + 1], path[i])) for i in range(len(path) - 1)]
    tangents = [segments[0]]
    for i in range(1, len(path) - 1):
        tangents.append(norm((segments[i - 1][0] + segments[i][0], segments[i - 1][1] + segments[i][1],
                              segments[i - 1][2] + segments[i][2])))
    tangents.append(segments[-1])

    # one reference vector, carried along: the first is whichever axis the path starts least aligned
    # with, and every ring after it takes the previous ring's own, re-squared against the new tangent
    start = tangents[0]
    seed = (0.0, 1.0, 0.0) if abs(start[1]) < 0.9 else (1.0, 0.0, 0.0)
    up = norm(cross(cross(start, seed), start))

    rings, lengths, travelled = [], [0.0], 0.0
    for index, (point, tangent) in enumerate(zip(path, tangents)):
        if index:
            up = norm(cross(cross(tangent, up), tangent))
            travelled += math.dist(path[index], path[index - 1])
            lengths.append(travelled)
        side = norm(cross(tangent, up))
        ring = []
        for i in range(sides):
            a = 2.0 * math.pi * i / sides
            c, s = math.cos(a), math.sin(a)
            offset = (up[0] * c + side[0] * s, up[1] * c + side[1] * s, up[2] * c + side[2] * s)
            ring.append(((point[0] + offset[0] * radius, point[1] + offset[1] * radius,
                          point[2] + offset[2] * radius), offset))
        rings.append(ring)

    span = uv_along
    for index in range(len(rings) - 1):
        v0 = lengths[index] / max(travelled, 1e-6) * span
        v1 = lengths[index + 1] / max(travelled, 1e-6) * span
        for i in range(sides):
            j = (i + 1) % sides
            a, b = rings[index][i], rings[index][j]
            c, d = rings[index + 1][j], rings[index + 1][i]
            u0 = i / sides * uv_scale
            u1 = (i + 1) / sides * uv_scale
            normal = ((a[1][0] + b[1][0]) * 0.5, (a[1][1] + b[1][1]) * 0.5, (a[1][2] + b[1][2]) * 0.5)
            mesh.quad(faces, (a[0], b[0], c[0], d[0]), normal,
                      ((u0, v0), (u1, v0), (u1, v1), (u0, v1)))

    if caps is not None:
        for ring, tangent, sign in ((rings[0], tangents[0], -1), (rings[-1], tangents[-1], 1)):
            normal = (tangent[0] * sign, tangent[1] * sign, tangent[2] * sign)
            corners = [point for point, _ in (ring if sign > 0 else list(reversed(ring)))]
            uvs = [(0.5 + 0.5 * math.cos(2.0 * math.pi * i / sides),
                    0.5 + 0.5 * math.sin(2.0 * math.pi * i / sides)) for i in range(sides)]
            mesh.quad(caps, corners, normal, uvs if sign > 0 else list(reversed(uvs)))


def arc(centre, radius, plane, start, end, steps):
    """Points round a quarter circle, for sweeping a bend along.

    ``plane`` names the two axes the turn happens in, as a pair of indices, and ``start`` and ``end``
    are angles in degrees measured in that plane.  The fixed axis keeps the centre's value.
    """
    a, b = plane
    fixed = 3 - a - b
    out = []
    for i in range(steps + 1):
        angle = math.radians(start + (end - start) * i / steps)
        point = [0.0, 0.0, 0.0]
        point[a] = centre[a] + math.cos(angle) * radius
        point[b] = centre[b] + math.sin(angle) * radius
        point[fixed] = centre[fixed]
        out.append(tuple(point))
    return out


def lathe(mesh, faces, centre, profile, sides=FITTING, uv_scale=1.0, uv_along=1.0):
    """A surface of revolution through a profile: the honest way to draw anything turned.

    ``profile`` is a list of ``(radius, height)`` in order from one end to the other, in the same units
    as ``centre``, and the surface is closed by construction - consecutive points are joined whatever
    their radii, so there is no way to leave a gap.

    Which is why the insulator is drawn this way now.  Built from stacked ``cylinder`` calls it had
    holes in it: a shed is a cone whose top is wider than the core above it, so between the two there was
    an annulus with nothing in it, and since the machines' render type does not cull back faces you
    could see straight through the porcelain.  A profile cannot have that fault - a radius that steps in
    draws the step.

    The uv runs once round the circumference and once along the profile by arc length, so a texture with
    a lit-cylinder gradient across it lands the same way on every part of the turning.
    """
    cx, cy, cz = centre
    if len(profile) < 2:
        return

    lengths, travelled = [0.0], 0.0
    for i in range(1, len(profile)):
        travelled += math.dist(profile[i], profile[i - 1])
        lengths.append(travelled)

    def point(index, i):
        radius, height = profile[index]
        a = 2.0 * math.pi * i / sides
        return (cx + math.cos(a) * radius, cy + height, cz + math.sin(a) * radius)

    for index in range(len(profile) - 1):
        r0, h0 = profile[index]
        r1, h1 = profile[index + 1]
        if r0 <= 1e-9 and r1 <= 1e-9:
            continue

        v0 = lengths[index] / max(travelled, 1e-9) * uv_along
        v1 = lengths[index + 1] / max(travelled, 1e-9) * uv_along
        # the outward normal of the band, which is the profile segment turned a quarter turn
        dr, dh = r1 - r0, h1 - h0
        span = math.hypot(dr, dh) or 1.0
        for i in range(sides):
            j = (i + 1) % sides
            a, b = point(index, i), point(index, j)
            c, d = point(index + 1, j), point(index + 1, i)
            mid = 2.0 * math.pi * (i + 0.5) / sides
            normal = (math.cos(mid) * dh / span, -dr / span, math.sin(mid) * dh / span)
            u0, u1 = i / sides * uv_scale, (i + 1) / sides * uv_scale
            # a band that closes onto the axis is a triangle, and the quad degenerates cleanly
            mesh.quad(faces, (a, b, c, d), normal, ((u0, v0), (u1, v0), (u1, v1), (u0, v1)))
